- application/stochastic-attention-head-removal-a-simple/README.md
- application/stochastic-attention-head-removal-a-simple/attention.py
- application/stochastic-attention-head-removal-a-simple/head_removal.py
> 【代码迁移】任务1：stochastic-attention-head-removal-a-simple

- application/group-normalization/README.md
- application/group-normalization/group_norm.py
> 【代码迁移】任务1：group-normalization

- application/ssFPN/README.md
- application/ssFPN/ssFPN.py
这是一个关于迁移**成功**代码的 PR, 现在此 PR 可供验收检查.
> 【代码迁移】任务3：ssFPN

- application/similarity-of-neural-network-representations-revisited/CKA.py
- application/similarity-of-neural-network-representations-revisited/README.md
_(最后修改时间 2024-9-19 07:53:20)_
这是一个关于迁移**成功**代码的 PR, 现在此 PR 可供验收检查.
> 【代码迁移】任务3：similarity-of-neural-network-representations-revisited

- application/coneheads-hierarchy-aware-attention/README.md
- application/coneheads-hierarchy-aware-attention/penumbral.py
- application/coneheads-hierarchy-aware-attention/umbral.py
> 【代码迁移】任务50：Coneheads: Hierarchy Aware Attention

- application/dropblock-a-regularization-method-for-convolutional-networks/README.md
> 【代码迁移】任务4：DropBlock: A regularization method for convolutional networks

- application/circle-loss/README.md
- application/circle-loss/circle_loss.py
> 【代码迁移】任务21：circle-loss

- application/NBC-Softmax/README.md
> 【代码迁移】任务5：NBC-Softmax

- application/hyperspherical-consistency-regularization/README.md
> 【代码迁移】任务5：hyperspherical-consistency-regularization

- application/layer-normalization/GRU_layernorm_cell.py
- application/layer-normalization/README.md
> 【代码迁移】任务50：Layer Normalizationadd

- application/layer-normalization/GRU_layernorm_cell.py
- application/layer-normalization/README.md
> 【迁移代码】任务50：layer-normalization

- application/matthews-correlation-coefficient-loss-for-deep-convolutional-networks-application-to-skin-lesion-segmentation/Example.ipynb
- application/matthews-correlation-coefficient-loss-for-deep-convolutional-networks-application-to-skin-lesion-segmentation/README.md
- application/matthews-correlation-coefficient-loss-for-deep-convolutional-networks-application-to-skin-lesion-segmentation/loss.py
在迁移代码中，已经有使用示例，所以未编写主函数
运行结果截图
> 【代码迁移】任务46：Matthews Correlation Coefficient Loss for Deep Convolutional Networks: Application to Skin Lesion Segmentation

- application/gated-word-character-recurrent-language-model/model.py
- application/gated-word-character-recurrent-language-model/readme.md
> 【代码迁移】任务36：Gated Word-Character Recurrent Language Model	

- application/root-mean-square-layer-normalization/README.md
- application/root-mean-square-layer-normalization/norm.py
- application/sa-mlp-distilling-graph-knowledge-from-GNNs-into-structure-Aware-MLP/README.md
- application/sa-mlp-distilling-graph-knowledge-from-GNNs-into-structure-Aware-MLP/model.py
> 【代码迁移】任务8：SA-MLP: Distilling Graph Knowledge from GNNs into Structure-Aware MLP

- application/a-self-attentive-model-for-knowledge-tracing/README.md
- application/a-self-attentive-model-for-knowledge-tracing/model.py
> 【代码迁移】任务20：A Self-Attentive model for Knowledge Tracing

- application/a-novel-segmentation-dataset-for-signatures-on-bank-checks/README.md
- application/a-novel-segmentation-dataset-for-signatures-on-bank-checks/dataloader.py
这是一个关于迁移**完成**代码的 PR, 现在此 PR 可供验收检查.
> 【代码迁移】任务9：A novel segmentation dataset for signatures on bank checks

- application/delving-deeper-into-convolutional-networks-for-learning-video-representations/Conv-GRU.py
- application/delving-deeper-into-convolutional-networks-for-learning-video-representations/README.md
这是一个关于迁移**完成**代码的 PR, 现在此 PR 可供验收检查.
> 【代码迁移】任务9：Delving Deeper into Convolutional Networks for Learning Video Representations

- application/fastformer-additive-attention-can-b-all-you-need/Fastformer.py
- application/fastformer-additive-attention-can-b-all-you-need/README.md
issue链接：https://gitee.com/mindspore/community/issues/IAPFT5
> 【代码迁移】任务1：Fastformer: Additive Attention Can Be All You Need

- application/refining-activation-downsampling-with-SoftPool/readme.md
- application/refining-activation-downsampling-with-SoftPool/softpool.py
> 【代码迁移】任务38 : refining activation downsampling with SoftPool

- application/SGDR: Stochastic Gradient Descent with Warm Restarts/CosineAnnealingWithRestartsLR.py
- application/SGDR: Stochastic Gradient Descent with Warm Restarts/readme.md
代码迁移任务39中的子任务1，issue链接为：https://gitee.com/mindspore/community/issues/IAPG9X，运行结果如下图：
> 【代码迁移】任务39 : SGDR: Stochastic Gradient Descent with Warm Restarts

- application/multimodal-trajectory-predictions-for-autonomous-driving-using-deep-convolutional-networks/README.md
- application/multimodal-trajectory-predictions-for-autonomous-driving-using-deep-convolutional-networks/mtp_loss.py
issue链接：https://gitee.com/mindspore/community/issues/IAPF6I
> 【代码迁移】任务7-2：multimodal-trajectory-predictions-for-autonomous-driving-using-deep-convolutional-networks

- application/optimize-coordconv/README.md
- application/optimize-coordconv/modules.py
issue链接为https://gitee.com/mindspore/community/issues/IAPF8W ,运行截图如下：
> 【代码迁移】任务10：An Intriguing Failing of Convolutional Neural Networks and the CoordConv Solution

- application/random_quantize/README.md
- application/random_quantize/randomized_quantization.py
issue链接为https://gitee.com/mindspore/community/issues/IAPF8W ,运行截图如下：
> 【代码迁移】任务10：Randomized Quantization: A Generic Augmentation for Data Agnostic Self-supervised Learning

- application/multi-task-learning-using-uncertainty-to/README.md
- application/multi-task-learning-using-uncertainty-to/code.py
issue链接：https://gitee.com/mindspore/community/issues/IAPG31
> 【代码迁移】任务37-2：MTL-Using-Uncertainty-to-Weigh-Losses

- application/effnet-an-efficient-structure-for-convolutional-neural-networks/README.md
- application/effnet-an-efficient-structure-for-convolutional-neural-networks/effnet.py
issue链接：https://gitee.com/mindspore/community/issues/IAPG31
> 【代码迁移】任务37-1：effnet-an-efficient-structure-for

- application/factorized-attention-self-attention-with-linear-complexities/README.md
- application/factorized-attention-self-attention-with-linear-complexities/efficient_attention.py
issue链接：https://gitee.com/mindspore/community/issues/IAPGIF
> 【代码迁移】任务43-1：efficient-attention

- application/fixed-classifier/README.md
- application/fixed-classifier/fixed_proj.py
Issue链接：https://gitee.com/mindspore/community/issues/IAPGKK
> 【代码迁移】任务44：Fix your classifier: the marginal value of training the last weight layer

- application/adam-aio/AdamAIO.py
- application/adam-aio/README.md
Issue链接：https://gitee.com/mindspore/community/issues/IAPGKK
> 【代码迁移】任务44：Decoupled Weight Decay Regularization

- application/squeeze-and-attention-networks-for-semantic/README.md
- application/squeeze-and-attention-networks-for-semantic/SABlock.py
issue:https://gitee.com/mindspore/community/issues/IAPFAC
> 【代码迁移】任务13-1：squeeze-and-attention-networks-for-semantic

- application/local-relation-networks-for-image-recognition/README.md
- application/local-relation-networks-for-image-recognition/layer.py
issue: https://gitee.com/mindspore/community/issues/IAPFAC
> 【代码迁移】任务13-2：Local Relation Networks for Image Recognition

- application/locally-consistent-deformable-convolution/README.md
- application/locally-consistent-deformable-convolution/def_conv.py
issue: https://gitee.com/mindspore/community/issues/IAPFU2
> 【代码迁移】任务33-1：locally-consistent-deformable-convolution

- application/multi-adversarial-domain-adaptation/README.md
- application/multi-adversarial-domain-adaptation/mada.py
issue: https://gitee.com/mindspore/community/issues/IAPFU2
> 【代码迁移】任务33-2：multi-adversarial-domain-adaptation

- application/effnet-an-efficient-structure-for-convolutional-neural-networks/README.md
- application/factorized-attention-self-attention-with-linear-complexities/README.md
- application/fastformer-additive-attention-can-b-all-you-need/README.md
- application/generalizing-and-decoupling-neural-collapse/README.md
- application/multi-task-learning-using-uncertainty-to/README.md
- application/multimodal-trajectory-predictions-for-autonomous-driving-using-deep-convolutional-networks/README.md
- application/open-domain-dialogue-quality-evaluation-deriving-nugget-level-scores-from-turn-level-scores/README.md
- application/openfashionclip-vision-and-language/README.md
> fix reame.md

- application/MCA/MCA.py
- application/MCA/README.md
> 【代码迁移】任务25：MCA

- application/contextual-learning-in-fourier-complex-field-for-VHR-remote-sensing-images/FCT.py
- application/contextual-learning-in-fourier-complex-field-for-VHR-remote-sensing-images/README.md
> 【代码迁移】任务25：Contextual Learning in Fourier Complex Field for VHR Remote Sensing Images

- application/swish-t/README.md
- application/swish-t/swisht.py
Issue链接：https://gitee.com/mindspore/community/issues/IAPFCT
> 【代码迁移】任务16：Swish-T : Enhancing Swish Activation with Tanh Bias for Improved Neural Network Performance

- application/stable-sam/README.md
- application/stable-sam/sam.py
- application/stable-sam/usam.py
Issue链接：https://gitee.com/mindspore/community/issues/IAPFCT
> 【代码迁移】任务16：Stabilizing Sharpness-aware Minimization Through A Simple Renormalization Strategy

- application/lcn-master-ms/local_context_norm_ms.py
Local Context Normalization: Revisiting Local Normalization
> 【代码迁移】任务42：Local Context Normalization: Revisiting Local Normalization

- application/LGL-INR-master/LGL-INR-master/LGLINR_ms.py
On the Learning Property of Logistic and Softmax Losses for Deep Neural Networks
> 【代码迁移】任务41：On the Learning Property of Logistic and Softmax Losses

- application/Lessons-on-Parameter-Sharing-across-Layers-in-Transformers/README.md
- application/Lessons-on-Parameter-Sharing-across-Layers-in-Transformers/pshare_transformer.py
- application/OTCE/README.md
- application/OTCE/otce.py
> 【代码迁移】任务17：Lessons on Parameter Sharing across Layers in Transformers

- application/Kronecker-Attention-Networks/README.md
- application/Kronecker-Attention-Networks/kronecker_attention.py
代码迁移任务40中的任务1，issue链接为：https://gitee.com/mindspore/community/issues/IAPGBO，运行结果如下图：
> 【代码迁移】任务40-1 : Kronecker Attention Networks

- application/privacy-enhancement-for-cloud-based-few-shot-learning/README.md
- application/privacy-enhancement-for-cloud-based-few-shot-learning/noise.py
> 【代码迁移】任务19：Privacy Enhancement for Cloud-Based Few-Shot Learning

- application/riemann-noise-ms-master/riemann-noise-ms-master/riemann-noise-ms/riemann_noise_ms.py
On Noise Injection in Generative Adversarial Networks
> 【代码迁移】任务41：On Noise Injection in Generative Adversarial Networks

- application/aves/README.md
- application/aves/aves-base-bio.json
- application/aves/aves.py
Issue链接：https://gitee.com/mindspore/community/issues/IAPFIS
> 【代码迁移】任务18：AVES: Animal Vocalization Encoder based on Self-Supervision

- application/smu/README.md
- application/smu/smu.py
Issue链接：https://gitee.com/mindspore/community/issues/IAPFIS
>  【代码迁移】任务18：SMU: smooth activation function for deep networks using smoothing maximum technique

- application/falformer/README.md
- application/falformer/feature_based_clustering.py
- application/falformer/kmeans.py
Issue链接：https://gitee.com/mindspore/community/issues/IAPFQ0
> 【代码迁移】任务26：FALFormer: Feature-aware Landmarks self-attention for Whole-slide Image Classification

- application/lru/README.md
- application/lru/lru.py
Issue链接：https://gitee.com/mindspore/community/issues/IAPFQ0
> 【代码迁移】任务26：Resurrecting Recurrent Neural Networks for Long Sequences

- application/Projected-Distribution-Loss-for-Image-Enhancement/README.md
- application/Projected-Distribution-Loss-for-Image-Enhancement/pdl.py
代码迁移任务24中的任务1，issue链接为：https://gitee.com/mindspore/community/issues/IAPFP3#note_32661816
输出结果为
> 【代码迁移】任务24-1 : Projected Distribution Loss for Image Enhancement

- application/vat/README.md
- application/vat/vat.py
Issue链接：https://gitee.com/mindspore/community/issues/IAPGOC
> 【代码迁移】任务49：Virtual Adversarial Training: A Regularization Method for Supervised and Semi-Supervised Learning

- application/cross-transformers-spatially-aware-few-shot-transfer/README.md
- application/cross-transformers-spatially-aware-few-shot-transfer/crosstransformers.py
> 【代码迁移】任务19：CrossTransformers

- application/iterative-a-de-blending/iadb.py
- application/misinfo-reaction-frames/demo.py
任务链接：https://gitee.com/mindspore/community/issues/IAPFVE
任务1:Misinfo Reaction Frames: Reasoning about Readers’ Reactions to News Headlines
任务2:Iterative α-(de)Blending: a Minimalist Deterministic Diffusion Model
任务1输出：
任务2输出：
> 【代码迁移】任务34：mrf与iadb

- application/fake-new-dectection/GCNN_main.py
- application/identifying-untrustworthy-prediction/CSM.py
- application/identifying-untrustworthy-prediction/main.py
【代码迁移】任务18:Identifying Untrustworthy Predictions 和 Fake new detection
任务链接：https://gitee.com/mindspore/community/issues/IAYPDR
任务二运行结果：
任务一运行结果：
任务一中from torch_geometric.datasets import TUDataset 仅做引用数据集，在网络中没有任何影响，前半部分已将该数据集转为mindspore可用格式。
> 【代码迁移】任务18:Identifying Untrustworthy Predictions 和 Fake new detection

- application/GAN-master/gan_ms.py
【代码迁移】任务29：NIPS 2016 Tutorial: Generative Adversarial Networks
> 【代码迁移】任务29：NIPS 2016 Tutorial: Generative Adversarial Networks

- application/lsuv-init/README.md
- application/lsuv-init/lsuv_init.py
issue：https://gitee.com/mindspore/community/issues/IAPFRZ
运行截图：
> 【代码迁移】任务30：All you need is a good init

- application/polyloss/APLLoss.py
- application/polyloss/README.md
issue：https://gitee.com/mindspore/community/issues/IAPFRZ
运行截图：
> 【代码迁移】任务30：PolyLoss: A Polynomial Expansion Perspective of Classification Loss Functions

- intern/Block_Model/README.md
- intern/Block_Model/block_model.py
- intern/PR_Product/PR.py
- intern/PR_Product/README.md
代码迁移2 任务36，issue链接为：https://gitee.com/mindspore/community/issues/IAYY5Z
PR Product: A Substitute for Inner Product in Neural Networks 的运行截图：
Block Model Guided Unsupervised Feature Selection 的运行截图:
> 【代码迁移】任务36: PR Product 和 Block Model

- application/gaussian_adaptive_attention/README.md
- application/gaussian_adaptive_attention/gaussian_adaptive_attention/GaussianBlock.py
- application/gaussian_adaptive_attention/gaussian_adaptive_attention/__init__.py
- application/gaussian_adaptive_attention/gaussian_adaptive_attention/main.py
1. 基于Mindspore复现了论文《Density Adaptive Attention is All You Need: Robust Parameter-Efficient Fine-Tuning Across Multiple Modalities》代码仓库的GaussianBlock、MultiHeadGaussianAdaptiveAttention、GaussianAdaptiveAttention类 （issue编号：https://gitee.com/mindspore/community/issues/IAYZGP   ）
2. 编写了main文件测试复现类的功能，测试任务为在MNIST数据集上训练一个带有GaussianBlock的简单网络。
3. 对比了不同网络的torch实现和mindspore实现的测试结果：
可见，基于Mindspore实现的GaussianBlock等类复现了基于Torch实现的效果。
> 【代码迁移】任务46：Density Adaptive Attention is All You Need: Robust Parameter-Efficient Fine-Tuning Across Multiple Modalities

- application/Class-balanced-loss-pytorch-master/class_balanced_loss_ms.py
【代码迁移】任务21：Class-Balanced Loss Based on Effective Number of Samples
> 【代码迁移】任务21：Class-Balanced Loss Based on Effective Number of Samples

- application/SeesawLoss-master/seesaw_loss_ms.py
【代码迁移】任务21：Seesaw Loss for Long-Tailed Instance Segmentation
> 【代码迁移】任务21：Seesaw Loss for Long-Tailed Instance Segmentation

- application/RAF-ms-main/raf_ms.py
【代码迁移】任务11：Transformers with Learnable Activation Functions
> 【代码迁移】任务11：Transformers with Learnable Activation Functions

- intern/Last-Query-Transformer-RNN/last_query_model.py
任务链接：https://gitee.com/mindspore/community/issues/IAYYBZ
> 【代码迁移】任务38-2：Last Query Transformer RNN for knowledge tracing

- application/DNN-with-SimulatedAnnealing/README.md
- application/DNN-with-SimulatedAnnealing/main.py
- application/DNN-with-SimulatedAnnealing/neural_network.py
- application/DNN-with-SimulatedAnnealing/simulated_annealing.py
运行结果：
issue链接：https://gitee.com/mindspore/community/issues/IAZ0U7?from=project-issue
> 【代码迁移】任务66-1:Output Range Analysis for Deep Neural Networks based on Simulated Annealing Processes

- intern/bi-tempered-loss-pytorch/README.md
- intern/bi-tempered-loss-pytorch/bi_tempered_loss.py
- intern/bi-tempered-loss-pytorch/fusion_result.json
- intern/bi-tempered-loss-pytorch/test_loss.py
Issue链接:https://gitee.com/mindspore/community/issues/IAZ0VQ
运行截图
> 【代码迁移】任务67：Robust Bi-Tempered Logistic Loss Based on Bregman Divergences	

- intern/Deformable_Patch_Representation/README.md
- intern/Deformable_Patch_Representation/deformable_patch_representation.py
任务链接https://gitee.com/mindspore/community/issues/IAZ0VQ
运行截图：
> 【代码迁移】任务67：Shape Matters: Deformable Patch Attack

- intern/iwae/README.md
- intern/iwae/iwae.py
任务链接：https://gitee.com/mindspore/community/issues/IAZ0XJ
运行截图：当n_sample为n时：
> 【代码迁移】任务71：Importance Weighted Autoencoders

- intern/dora/README.md
- intern/dora/dora.py
任务链接:https://gitee.com/mindspore/community/issues/IAZ0XJ
运行截图：
> 【代码迁移】任务71：DoRA: Weight-Decomposed Low-Rank Adaptation

- intern/SING/SING.py
- intern/SING/main.py
- intern/SING/readme.md
论文实现了一种由Adam改进而来的优化器SING。原pytorch中的代码没有main函数。将SING使用mindspore实现后，在MINST数据集上做了验证。训练效果如下：
> 【代码迁移】任务14-2：SING: A Plug-and-Play DNN Learning Technique

- intern/Datasets-Models-main/Models.py
- intern/Datasets-Models-main/README.md
> 【代码迁移】任务70： Communication-Efficient Hierarchical Federated Learning

- intern/VAE-Creative-Discovery-using-QD-Search/VAE2.py
【代码迁移】任务60-2：Creative Discovery using QD Search
任务链接：https://gitee.com/mindspore/community/issues/IAZ0IS
test输出结果如下：
> 【代码迁移】任务60-2：Creative Discovery using QD Search

- application/Generating Sequences With Recurrent Neural Networks/rnns.py
> 【代码迁移】任务15：Generating Sequences With Recurrent Neural Networks

- application/Two-Layer-ReLU-Network-Analytically/anmin.py
> 【代码迁移】任务49-2:Training a Two Layer ReLU Network Analytically

- intern/Knowing-When-to-Look-Adaptive-Attention/adaptive_attention.py
【代码迁移】任务41-1：Knowing When to Look: Adaptive Attention via A Visual Sentinel for Image Captioning
ISSUE链接：https://gitee.com/mindspore/community/issues/IAYYX6
输出结果如下，模型结果正常输出：
> 【代码迁移】任务41-1：Knowing When to Look: Adaptive Attention via A Visual Sentinel for Image Captioning

- application/Scalable-Sharpness-Aware-Minimization/looksam.py
在原代码和迁移代码中用相同的简单网络结构测试，torch的测试代码：
```python
class SimpleModel(nn.Module):
def __init__(self):
super(SimpleModel, self).__init__()
self.linear = nn.Linear(10, 1)
def forward(self, x):
return self.linear(x)
data = torch.randn(100, 10)
targets = torch.randn(100, 1)
dataset = torch.utils.data.TensorDataset(data, targets)
loader = torch.utils.data.DataLoader(dataset, batch_size=32)
model = SimpleModel()
criterion = nn.MSELoss()
base_optimizer = optim.SGD
optimizer = LookSAM(k=10,
alpha=0.7,
model=model,
base_optimizer=base_optimizer,
criterion=criterion,
rho=0.05,
lr=0.01)
for epoch in range(2):
for train_index, (samples, targets) in enumerate(loader):
outputs = model(samples)
loss = criterion(outputs, targets)
loss.backward()
optimizer.step(t=train_index, samples=samples, targets=targets, …
```
> 【代码迁移】任务68-1:Towards Efficient and Scalable Sharpness-Aware Minimization

- intern/pixelshuffle1d/README.md
- intern/pixelshuffle1d/demo.py
- intern/pixelshuffle1d/pixelshuffle1d.py
任务链接：https://gitee.com/mindspore/community/issues/IAYZ4O
运行截图：
> 【代码迁移】任务44：Real-Time Single Image and Video Super-Resolution Using an Efficient Sub-Pixel Convolutional Neural Network

- application/gdn/README.md
- application/gdn/gdn.py
- application/gdn/main.py
1. 基于Mindspore复现了论文《End-to-end Optimized Image Compression》代码仓库的GDN等类 （issue编号：https://gitee.com/mindspore/community/issues/IAYYOG ）
2. 编写了main文件测试复现类的正常运行，并且编写了测试函数测试与Pytorch实现的功能一致性。
3. 验证与Pytorch实现的功能一致性的结果：
可知Mindspore结果与Pytorch结果差异在十万分之一以内，说明功能一致。
> 【代码迁移】任务40：End-to-end Optimized Image Compression

- application/Neural Side-by-Side/LICENSE
- application/Neural Side-by-Side/README.md
- application/Neural Side-by-Side/model.py
【代码迁移】任务64-1：Neural Side-by-Side: Predicting Human Preferences for No-Reference Super-Resolution Evaluation
> 【代码迁移】任务64-1：Neural Side-by-Side: Predicting Human Preferences for No-Reference Super-Resolution Evaluation

- intern/Luminance-Guided-Chrominance-Enhancement-for-HEVC-Intra-Coding/README.md
- intern/Luminance-Guided-Chrominance-Enhancement-for-HEVC-Intra-Coding/network.py
- intern/Luminance-Guided-Chrominance-Enhancement-for-HEVC-Intra-Coding/submodule.py
- intern/Luminance-Guided-Chrominance-Enhancement-for-HEVC-Intra-Coding/test.py
任务链接：https://gitee.com/mindspore/community/issues/IAZ0FW
测试运行截图：
与pytorch下测试运行截图基本一致：
> 【代码迁移】任务55: Luminance-Guided Chrominance Image Enhancement for HEVC Intra Coding

- intern/RGNN/README.md
- intern/RGNN/model_simple.py
- intern/RGNN/test.py
任务链接：https://gitee.com/mindspore/community/issues/IAYZ4O
运行截图：
> 【代码迁移】任务44：EEG-Based Emotion Recognition Using Regularized Graph Neural Net

- application/DropMax-Adaptive-Variational-Softmax/dropmax.py
原代码就运行就有点问题，Loss 是 NaN，迁移代码按照一比一复刻，MNIST 数据集采用官方文档的加载方式。
原论文代码运行：
迁移代码：
> 【代码迁移】任务 20-1：DropMax: Adaptive Variational Softmax

- application/Generalized-End-to-End-Loss-for-Speaker-Verification/ge2e.py
> 【代码迁移】任务27-1：Generalized End-to-End Loss for Speaker Verification

- application/Efficient ConvBN Blocks for Transfer Learning and Beyond/tune_mode_convbn.py
- application/Spatial and Temporal Mutual Promotion for Video-based Person Re-identification/ruu.py
> 【代码迁移】任务11-1:Spatial and Temporal Mutual Promotion for Video-based Person Re-identification

- intern/Profiling-Pareto-Front/README.md
- intern/Profiling-Pareto-Front/ms_moosvgd.py
- intern/Profiling-Pareto-Front/ms_run_zdt_moosvgd.py
- intern/Profiling-Pareto-Front/ms_zdt_functions.py
issue：https://gitee.com/mindspore/community/issues/IAYYBZ
> 【代码迁移】任务37-2：Profiling Pareto Front With Multi-Objective Stein Variational Gradient Descent

- intern/Hyena-A-Convolutional-Neural-Network-for-Modelling-Sentences/hyena.py
【代码迁移】任务72-1：A Convolutional Neural Network for Modelling Sentences
ISSUE链接：https://gitee.com/mindspore/community/issues/IAZ0Y0
复现代码能够正常运行并输出训练过程：
> 【代码迁移】任务72-1：A Convolutional Neural Network for Modelling Sentences

- intern/SMOTE/README.md
- intern/SMOTE/smote_mindspore.py
> 【代码迁移】任务5-1：SMOTE: Synthetic Minority Over-sampling Technique

- intern/PolyLoss/README.md
- intern/PolyLoss/polyloss_mindspore.py
- intern/PolyLoss/test_polyloss.py
> 【代码迁移】任务5-2：PolyLoss: A Polynomial Expansion Perspective of Classification Loss Functions

- intern/MicAugment/README.md
- intern/MicAugment/mic_augment_mindspore.py
- intern/MicAugment/test_mic_augment.py
> 【代码迁移】任务6-1：MicAugment: One-shot Microphone Style Transfer

- application/fisheradversarial-mindspore/README.md
- application/fisheradversarial-mindspore/fisherform.py
- application/fisheradversarial-mindspore/fishertrace.py
- application/fisheradversarial-mindspore/setup.py
- application/fisheradversarial-mindspore/usage.py
- intern/fisheradversarial-mindspore/README.md
- intern/fisheradversarial-mindspore/fisherform.py
- intern/fisheradversarial-mindspore/fishertrace.py
- intern/fisheradversarial-mindspore/setup.py
- intern/fisheradversarial-mindspore/usage.py
> 【代码迁移】任务17 2： inspecting adversarial examples using the fisher information

- application/nystrom-attention/nystrom_attention/_init_.py
- application/nystrom-attention/nystrom_attention/nystrom_attention.py
- application/nystrom-attention/setup.py
- application/nystrom-attention/test_attn.py
- application/nystrom-attention/test_model.py
- intern/nystrom-attention/nystrom_attention/_init_.py
- intern/nystrom-attention/nystrom_attention/nystrom_attention.py
- intern/nystrom-attention/setup.py
- intern/nystrom-attention/test_attn.py
- intern/nystrom-attention/test_model.py
【代码迁移】任务23-2：nystrom-attention
> 【代码迁移】任务23-2：nystrom-attention

- application/D-Unet_Mindspore/DUnet.py
- application/D-Unet_Mindspore/DUnet_parts.py
- application/D-Unet_Mindspore/loss.py
- application/D-Unet_Mindspore/workspace_test.py
- intern/D-Unet_Mindspore/DUnet.py
- intern/D-Unet_Mindspore/DUnet_parts.py
- intern/D-Unet_Mindspore/loss.py
- intern/D-Unet_Mindspore/workspace_test.py
> 【代码迁移】任务23-1：D-Unet_Mindspore

- application/On-the-Convergence-of-AdaBound-and-its-Connection-to-SGD/csgd.py
已在代码中使用简单网络测试
```python
class SimpleNet(nn.Cell):
def __init__(self, input_dim, output_dim):
super(SimpleNet, self).__init__()
self.fc = nn.Dense(input_dim, output_dim)
def construct(self, x):
return self.fc(x)
loss_fn = nn.MSELoss()
net = SimpleNet(input_dim=10, output_dim=1)
net_with_loss = nn.WithLossCell(net, loss_fn)
optimizer = CSGD(net.trainable_params(), learning_rate=0.1, momentum=0.9, weight_decay=0.01)
x_np = np.arange(50, dtype=np.float32).reshape(5, 10)
target_np = np.arange(5, dtype=np.float32).reshape(5, 1)
x = Tensor(x_np)
target = Tensor(target_np)
grad_fn = mindspore.value_and_grad(net_with_loss, None, net.trainable_params(), has_aux=False)
def train_step(x, target):
loss, grads = grad_fn(x, target)
optimizer(grads)
return loss
loss_val = train_step(x, target) …
```
> 【代码迁移】任务35-1：On the Convergence of AdaBound and its Connection to SGD

- application/jko_wass_grad/jko_gradient_mindspore.py
- application/jko_wass_grad/jko_wass_grad_mindspore.py
- application/jko_wass_grad/pth2pkl.py
> 【代码迁移】任务2-2：Convergence of flow-based generative models via proximal gradient descent in Wasserstein space

- application/PyDSN/demo.py
- application/PyDSN/loss_mindspore.py
输入为标准正态分布
torch输出：
mindspore输出：
二者结果基本一致（输入为标准正态分布下随机变量）
> 【代码迁移】任务15-1：Interpretable modulated differentiable STFT and physics-informed balanced spectrum metric

- intern/A-Note-on-the-Inception-Score/README.md
- intern/A-Note-on-the-Inception-Score/inception_score.py
> 【代码迁移】任务7-1：A-Note-on-the-Inception-Score

- intern/SelectiveBackPropagation-master/README.md
- intern/SelectiveBackPropagation-master/selective_back_propagation_MS.py
This code is a mindspore implementation of Selective_Backpropagation
> 【代码迁移】任务53-2：Selective_Backpropagation

- intern/DietNetworks-master/README.md
- intern/DietNetworks-master/dietnetworks_ms.py
- intern/DietNetworks-master/main_ms.py
- intern/DietNetworks-master/training_ms.py
This code is a mindspore implementation of DietNetworks-master
> 【代码迁移】任务48-2：DietNetworks-master

- intern/FD-CAM/README.md
- intern/FD-CAM/fdcam_mindspore.py
- intern/FD-CAM/main_ms.py
This code is a mindspore implementation of FD-CAM
> 【代码迁移】任务48-1：FD-CAM
